export const enviroment = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  SUPABASE_PROJECT_URL: process.env.NEXT_PUBLIC_SUPABASE_API_KEY,
  SUPABASE_API_KEY: process.env.NEXT_PUBLIC_SUPABASE_API_KEY,
};
